### ISSUE TITLE
Fails To Run After Install

### ISSUE THREAD

**Issue by fpall** [christ0ph3r/cryptocurrency-cli#7]
[npm-debug.log](https://github.com/christ0ph3r/cryptocurrency-cli/files/1777723/npm-debug.log)
[npm-debug.log](https://github.com/christ0ph3r/cryptocurrency-cli/files/1777724/npm-debug.log)

After following the install, I receive the attached errors. I have the latest versions of node and npm installed. I'm running Ubuntu 16.04. Please have a look and let me know. Thanks -

**Comment by christ0ph3r** [comment]
Please copy the error log to a gist or pastebin so I can view without downloading.  Thanks.

@fpall

**Comment by fpall** [comment]
Hi - Here you go: https://gist.github.com/fpall/c51baa7df25aa9446b227110c85a8ad9
Please let me know if you need anything else from my end. Thx!
@christ0ph3r

**Comment by christ0ph3r** [comment]
Noone else has said this and it gets a lot of downloads per day.  If someone else is having the same issue, it would be great if they can chime in.  I think this is more likely to do with your NPM/Node config.  You said you have the latest versions.

If you type `npm -v` and `node -v`, what do you get? npm 3.5.2
and node v4.2.6? because that is what I see in your logs and those and those are not the latest versions, those are pretty old.

**Comment by fpall** [comment]
@christ0ph3r thanks...i updated to v9.9.0 and all is working. Appreciate it.

**Comment by christ0ph3r** [comment]
Great to hear, cheers @fpall
